# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  messagingsampleapplicationserver:
    image: messagingsampleapplicationserver
    build:
      context: .
      dockerfile: src/MessagingSample.ApplicationServer/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5021:5021
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
