version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_PASSWORD=postgresql

  messagingsampleapplicationserver:
    image: messagingsampleapplicationserver
    build:
      context: .
      dockerfile: src/MessagingSample.ApplicationServer/Dockerfile
    ports:
      - 5021:80
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ__HOSTNAME=rabbitmq
      - SQLCONNSTR_AppDB=Host=db;Database=app_db;Username=postgres;Password=postgresql

  messagingsamplebackgroundservice:
    image: messagingsamplebackgroundservice
    build:
      context: .
      dockerfile: src/MessagingSample.BackgroundService/Dockerfile
    ports:
      - 5022:80
    depends_on:
      - rabbitmq
      - db
    environment:
      - RABBITMQ__HOSTNAME=rabbitmq
      - SQLCONNSTR_AppDB=Host=db;Database=app_db;Username=postgres;Password=postgresql
